# Modified by Je'aime Powell 4/11/23  
# Jekyl Theme:  Affiliates - https://wowthemesnet.github.io/affiliates-jekyll-theme/

title: "Code@MS-CC23"
description: > 
  This page will serve as the event site for the Code@MS-CC23 Student Hackathon held May 9th - 10th, 2023 in Atlanta, GA at the 2023 Minority Serving - Cyberinfrastructure Consortium (MS-CC) Annual Meeting.
#title: "Affiliates"
email: schack@hackhcp.org
timezone: EST #UTC

baseurl: "/codeatms-cc23" # the subpath of your site, e.g. /blog
url: "https://hackhpc.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

#baseurl: "/affiliates-jekyll-theme"
permalink: "/:title/"

logo: assets/imgs/logos/MS-CC_Logo.png #'assets/imgs/ms-cccolorssm-text.png'
favicon: 'assets/imgs/ms-cccolorssm.ico'
headerimage: 'assets/imgs/CodeatMS-CC-header-trs.png'
headerbackground: 'assets/imgs/atlskyline-alt.jpg' #This is linked to the hero_img class in theme.scss

#twitter_username: ccloudhack
#instagram_username: schack@hackhcp.org
#facebook_username: mauricio.urraco
#linkedin_username: https://www.linkedin.com/groups/8859728/
#github_username:  HackHPC
#youtube_page: https://www.youtube.com/@hackhpc2069
#registration_link: https://service5.internet2.edu/reg/events/MSCC-0523/registrations

host_event_name: MS-CC Hackathon
host_event_link: https://www.ms-cc.org/2023-annual-meeting#h.h3rnrkpqy63d

# Social
social:
  linkedin: https://www.linkedin.com/groups/8859728/
  #instagram: https://www.instagram.com/bootstrapstarter/
  #facebook: https://www.facebook.com/bootstrapstartercom-346329609045284
  twitter: https://twitter.com/ccloudhack
  github:  https://github.com/HackHPC
  youtube: https://www.youtube.com/@hackhpc2069


author: HackHPC
paginate: 30
disqus: 'demowebsite'
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: UA-113961478-1

# Authors
authors:
  HackHPC:
    name: HackHPC
    display_name: HackHPC
    avatar: 'assets/hack-logo.png'
    email: schack@hackhcp.org
    web: http://hackhpc.org
    twitter: https://twitter.com/ccloudhack
    description: "HackHPC is a group of High-Performance Computing professionals dedicated to increasing applied knowledge and skills in a diverse workforce through the use of hackathon methodologies. Est. 2018"
  
  
organizers: 
  
  - name:           Teniola Agbesanwa
    affiliation:    "Minority Serving - Cyberinfrastructure Consortium (MS-CC)"
    site:           https://www.ms-cc.org
    #linkedin:       https://www.linkedin.com/in/amy-cannon-46230b31/
    avatar:         assets/imgs/organizers/Teni-Agbesanwa.jpeg
    bio:            "Teni supports the MS-CC’s program implementation through relationship building, marketing, and communications to increase engagement efforts around advancing cyberinfrastructure across historically Black colleges and universities (HBCUs) and tribal colleges and universities (TCUs). Before this role, Teni had experience working in higher education and k-12 schools."
    email:          tagbesanwa@internet2.edu
    #twitter:        https://twitter.com/amy__cannon
    #github: 
  
  - name:           Russell Hofmann
    affiliation:    "Minority Serving - Cyberinfrastructure Consortium (MS-CC)"
    site:           https://www.ms-cc.org
    #linkedin:       https://www.linkedin.com/in/amy-cannon-46230b31/
    #avatar:         assets/imgs/organizers/amy-sq.png
    #bio:            "Amy Cannon has worked at Omnibond for 10 years, where her Business Development skills allow her to engage with customers and partners, teaching how HPC and Cloud help solve scientific problems. Outside of work she enjoys spending time in nature as well as helping others grow their HPC, HTC, AI, and Cloud Computing knowledge."
    email:          rhofmann@internet2.edu
    #twitter:        https://twitter.com/amy__cannon
    #github: 
  
  - name:           Charlie Dey
    affiliation:    "Texas Advanced Computing Center"
    site:           https://www.tacc.utexas.edu/about/directory/charlie-dey
    linkedin:       https://www.linkedin.com/in/charlie-dey-0031317a/
    avatar:         assets/imgs/organizers/charlie-dey.jpeg
    bio:            "Charlie Dey(he/him) is the Director of Training and Professional Development with the User Services group at the Texas Advanced Computing Center(TACC) with a background in web development and scientific computing.  Charlie’s responsibilities at TACC include organizing, developing content, and building curriculums for TACC’s academic course selection taught in conjunction with several departments at the University of Texas at Austin, as well as for TACC’s professional development and educational training. Prior to joining TACC, he worked as a Senior Application Developer for the Carle Foundation Hospital, and as a computer science instructor at Parkland College in Champaign, IL.  He was also a member of a specialized application development team at the University of Illinois and has been a contracted research consultant for NASA Ames Research Center, studying computational immunology and bioinformatics. Charlie holds a Bachelor’s Degree concentrating in Computer Science and Biology from Eastern Illinois University, and certifications in 3D programing and visualization. He is currently finishing up a Master’s of Science in Cybersecurity."
    email:          charlie@tacc.utexas.edu
    twitter:        https://twitter.com/DeyCharlie
    github:         https://github.com/ubik10


   
  - name:           Amy Cannon
    affiliation:    "Omnibond"
    site:           http://www.omnibond.com/
    linkedin:       https://www.linkedin.com/in/amy-cannon-46230b31/
    avatar:         assets/imgs/organizers/amy-sq.png
    bio:            "Amy Cannon has worked at Omnibond for 10 years, where her Business Development skills allow her to engage with customers and partners, teaching how HPC and Cloud help solve scientific problems. Outside of work she enjoys spending time in nature as well as helping others grow their HPC, HTC, AI, and Cloud Computing knowledge."
    email:          amycannon@omnibond.com
    twitter:        https://twitter.com/amy__cannon
    github:         https://hackhpc.github.io/ 

 # - name:           Dr. Linda Hayden
 #   affiliation:    "Science Gateways Community Institute"
 #   site:           https://sciencegateways.org/
 #   linkedin:       https://www.linkedin.com/in/linda-hayden-5a8b424/
 #   avatar:         assets/imgs/organizers/linda.jpeg
 #   bio:            "Dr. Linda Hayden holds a Ph.D. in Mathematics and Education. She leads workforce development activities for the NSF Science Gateways Community Institute (SGCI). In that position she works to train the next generation of gateway developers and users. Professor Hayden is an NSF Presidential Awardee for Excellence in Science, Mathematics and Engineering Mentoring."
 #   email:          haydenl@mindspring.com
 #   twitter:        https://twitter.com/lhaydenecsu
 #   github:         https://hackhpc.github.io/ 

  - name:           Alexander Nolte
    affiliation:    "University of Tartu"
    site:           https://alexandernolte.github.io/
    linkedin:       https://www.linkedin.com/in/alexandernolte/
    avatar:         assets/imgs/organizers/alex.jpeg
    bio:            "Alex is an Associate Professor at the University of Tartu and an Adjunct Associate Professor at Carnegie Mellon University working in the are of human computer interaction. He is an avid hackathon enthusiast and has participated in, co-organized, served as a mentor and studied countless hackathons over the past years with no end in sight. Outside of work he fiddles with any gadget he can get his hand on, plays video games, cooks and does BBQ."
    email:          alexander.nolte@ut.ee
    twitter:        https://twitter.com/alexander_nolte/
    github:         https://github.com/alexandernolte

  - name:           Je'aime Powell
    affiliation:    "Texas Advanced Computing Center"
    site:           https://jeaimehp.github.io/
    linkedin:       https://www.linkedin.com/in/jeaimehp/
    avatar:         assets/imgs/organizers/jeaime-sq.png
    bio:            "Je’aime is a Systems Administrator and a researcher at the Texas Advanced Computing Center. When not working on high-perfomance/cloud compute systems or mentoring students you can find him designing, creating, and/or deploying enviromental sensors."
    email:          jpowell@tacc.utexas.edu
    twitter:        https://twitter.com/jeaimehp
    github:         https://github.com/jeaimehp 

  - name:           Boyd Wilson
    affiliation:    "Omnibond"
    site:           http://www.omnibond.com/
    linkedin:       https://www.linkedin.com/in/boydwilson/
    avatar:         assets/imgs/organizers/boyd.png
    bio:            "Boyd Wilson, CEO of Omnibond Systems, has extensive experience and leadership in the areas of software development, system administration, storage architectures and business models. Formerly, Boyd served as Software CTO and also Executive Director over computing operations at Clemson University and had research computing as part of his purview. He has participated in various academic grants, papers and workshops in the areas of parallel storage, cloud computing and computational infrastructure. Boyd’s current focus lies in 4 areas: first- computer vision, ai, and real-time traffic analytics with TrafficVision; second- high-performance computing and storage with CloudyCluster and OrangeFS; third- identity and security management; fourth- wake surfing and riding a boosted board around cities while traveling."
    email:          boyd@omnibond.com
    twitter:        https://twitter.com/boydwilson/
    github:         https://github.com/omnibond/




# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives